### ISSUE TITLE
sometimes message does not move up

### ISSUE THREAD

**Issue by evermeer** [yoavlt/PeriscommentView#5]
When entering a 2nd message, then sometimes the previous message does not move up. The 2nd message will then overlay the first message. In my case this happens one in every 5 times.

When there are already 2 messages in the screen, then the behavior is sometimes that the 1st message is moving up, the 2nd message stays in it's place and the 3rd message will overlay the 2nd message. Between the 1st and the 2nd and 3rd message there will be a gap the size of message 2 that should have been at that spot.

**Comment by swamiphoto** [comment]
I have the same issue.

**Comment by orkhanalizade** [comment]
@evermeer @swami-108 I just answered to that question [here](http://stackoverflow.com/questions/41324300/swift-animation-for-periscope-style-comments/41330014#41330014)

**Comment by salmank888** [comment]
Please see this in detail, its behaviour is not continuous, but it troubles when at same time a cell is hiding and you add a new cell on it.

For example if we increase "disappearDuration" to a higher value say **15 seconds**, up to that time it will work properly but when it approaches that time (15 seconds) and you are continuously adding a cell after 3 seconds then **7th** cell to populate will start troubling here.

here is a [video](https://streamable.com/6t08s) showing some behaviour of it, with "disappearDuration" to be **7 seconds**.

Following instructions on the [link](https://stackoverflow.com/questions/41324300/swift-animation-for-periscope-style-comments/41330014#41330014) given above, I did not tried to "rewrite the functionality". -> but i still have this issue.

Please see it in detail and help if you can...

Waiting for your reply...
